# Generated by Django 5.2 on 2025-04-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
