# Generated by Django 5.2 on 2025-04-20 13:12

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=orders.models.generate_unique_order_id, editable=False, max_length=20, unique=True),
        ),
    ]
